### ISSUE TITLE
license

### ISSUE THREAD

**Issue by werdahias** [RobertWinslow/Simple-SVG-to-Font-with-Fontforge#1]
I want to use this in another project, how is this licensed ?

**Comment by RobertWinslow** [comment]
If you're just using the script, I claim no ownership over any fonts you create with it.

If you plan to modify/redistribute the script itself, I've added a little bit of copyright info at the top of the file. 

Either way, if you do end up using it, I'd love to see what you use it for.  [Leave a comment here, if you please.](https://github.com/RobertWinslow/Simple-SVG-to-Font-with-Fontforge/issues/2)
