### ISSUE TITLE
No module named 'fontforge'

### ISSUE THREAD

**Issue by shaovoon** [RobertWinslow/Simple-SVG-to-Font-with-Fontforge#3]
Hi Robert,

Thank you for writing this script.

I have installed Python3 and FontForge on Windows 10 but when I run your script with your svg folder, I encountered this python error:

```
    import fontforge
ModuleNotFoundError: No module named 'fontforge'
```

How do I find this python fontforge module?

Thanks in advance.

**Comment by shaovoon** [comment]
I am using Mac and Windows. I resolved this issue by using this SO answer: https://stackoverflow.com/questions/32688726/pip-install-fontforge-says-couldnot-find-a-version

The answer is a bit outdated so I'll list the steps I took to resolve this issue. 

I installed Ubuntu 2404 LTS on Windows using WSL. Then I upgrade the Ubuntu's libraries and install dev tools that includes Python3.

```
sudo apt update
sudo apt upgrade
sudo apt install build-essential
```

Then I install FontForge Python3 module.

```
sudo apt install python3-fontforge
```

Then I run Python3 to check the presence of fontforge module.

```
python3 -c "import fontforge;print(fontforge)"
```

If fontforge exists, its path will be printed.

**Comment by RobertWinslow** [comment]
I'm glad you were able to resolve the issue. 

Were you using fontforge to run the script with the following command? 

`fontforge -script build_simple_black_font_with_fontforge.py`

By default, I believe fontforge creates its own python environment, and it doesn't install the fontforge module to your default python environment. So if you try to run the script using `python3 ...` or something along those lines, you'll run into this missing module issue.

On the other hand, if you *were* using `fontforge ...` to run things, then I have no idea what went wrong. Thanks for typing up your solution.
